template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_test_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_test_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: maven_test_pipeline
    steps:
      - name: mvn_test_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          inputResources:
            - name: mvn_test_repo
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_test_build  
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_test_build_step
          outputResources:
            - name: mvn_test_build_info
          integrations:
            - name: {{ .Values.smtpIntegration }}  
          execution:
            onSuccess:
              - send_notification {{ .Values.smtpIntegration }} --recipients "pruthvi94rb@gmail.com" --subject "Build Succeeded" --body "build details:$PIPELINE_NAME.$RUN_NUMBER"


            
      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
            - name: mvn_test_build_info 
