gitProvider: Pipelinescantest
artifactory: amithmutak
artifactoryUrl: amithmutak.jfrog.io   # replace with your server name
repoPath: sandeepani2206/testpipeline     # replace jfrog with your username or org name
deployerRepo: maven-local
